### ISSUE TITLE
Crash (a few waves in)

### ISSUE THREAD

**Issue by THB0705** [8BitToaster/Block-Tower-Defense#2]
**Describe the bug**
C**_rash, looking at screenshot it seems to be a very simple typo!!_**

**To Reproduce**
I was just letting the game play on auto mode, it was fine until suddenly the error below occurred.

**Expected behavior**
Game should continue running.

**Screenshots**
![issue](https://user-images.githubusercontent.com/42702031/70802911-0fd21880-1db3-11ea-9622-a7f07240f2bc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by SophieWalden** [comment]
Has been fixed, sorry for the bug. I've also split the waves into a separate file, made a button just for setting to make it more clear, and added the outline of the button for the start to make it more clear it's a start button.

-8Bittoaster
